language: node_js
node_js:
  - "node"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
#  - npm run lint
  - npm run test:headless
  - npm run build:prod
#  - xvfb-run npm run e2e